apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: demo-l2-network
  namespace: networking-altug-demo-project2
spec:
  config: |2
    {
            "cniVersion": "0.3.1", 
            "name": "demo-l2-network", 
            "type": "ovn-k8s-cni-overlay", 
            "topology":"layer2", 
            "mtu": 1300, 
            "netAttachDefName": "networking-altug-demo-project2/demo-l2-network" 
    }