apiVersion: k8s.cni.cncf.io/v1beta1
kind: MultiNetworkPolicy
metadata:
  annotations:
    k8s.v1.cni.cncf.io/policy-for: l2-network
  name: deny-all
  namespace: networking-altug-demo-project2
spec:
  podSelector: {}
  ingress: []
  policyTypes:
    - Ingress